### ISSUE TITLE
Refactor Assertion Statements To Use isinstance And Use raise Exceptions

### ISSUE THREAD

**Issue by mattsthilaire** [mnansary/bnUnicodeNormalizer#12]
Hello!

I've been working with you library for the [Bengali Audio Competition on Kaggle](https://www.kaggle.com/competitions/bengaliai-speech), and I decided to take a dive into the source code. 

I noticed there were a few assert statements in the BaseNormalizer class, proposing we change those to use isinstance for type checking, and then raise statements for errors. One example would be:

`assert type(language)==str,"language is not string type!!!"`

->

```
if not isinstance(language, str):
    raise TypeError("language is not string type!!!")
```

**Comment by mnansary** [comment]
Hello , Thanks for the great suggestion. Sorry for the late reply. The repo has been stale for a long time. This year the work is accepted in Lrec-Coling so we will manage such works in future hopefully
