### ISSUE TITLE
log:normalized text can not be formed for

### ISSUE THREAD

**Issue by ArupDas15** [mnansary/bnUnicodeNormalizer#2]
Hello,
I am seeing the below logs for certain Bengali documents:
![image](https://user-images.githubusercontent.com/37553488/156499847-6c1d9bae-f6b5-4c6b-962a-a90d0ebb2226.png)
I would like to know in this case if normalization is not possible then does the normalizer return the text as it? What does it do when it cannot normalize?

**Comment by mnansary** [comment]
Hi , can you please share the texts? The following part is the relevant part i believe.. while executing the normalization operations if the text lenght becomes 0 for some reason (removing invalid endings/ startings) this log is shown and then it returns None
the last part of the log should also print the text where normalization is failing. 
```python
for op in ops:
    if not self.__checkOp(op):
        print(f"log:normalized text can not be formed for {text}")
        return None
```
