### ISSUE TITLE
unsupported operand type(s) for +=: 'NoneType' and 'str' at /bnunicodenormalizer/base.py:226

### ISSUE THREAD

**Issue by ShahriarDhruvo** [mnansary/bnUnicodeNormalizer#5]
```
আলেক্সান্দ্‌‌র
আল‌‌-কোরআন
তর্‌‌রিচেল্লি
বলবো‌‌‌
বলব‌‌‌
বল্‌চ্‌‌
বিটলস‌‌
সল‌ঝেনিত্‌‌সিন
```

If you pass these words one by one it will give this error.

**Comment by mnansary** [comment]
thanks for the issue. Fixed in v-0.0.18. https://pypi.org/project/bnunicodenormalizer/
issue description: no space characters 
example:
```
'আলেক্সান্দ্‌‌র' breaks as : ['আ', 'ল', 'ে', 'ক', '্', 'স', 'া', 'ন', '্', 'দ', '্', '\u200c', '\u200c', 'র']
'বল্‌চ্‌‌' beaks as:['ব', 'ল', '্', '\u200c', 'চ', '্', '\u200c', '\u200c']
```
remedy: 
* normalize \u200c to \u200d 
* only allow : 'র', '\u200d',  as 'র‍্য'
* remove connectors in between no space chars
