### ISSUE TITLE
ফ্যামিলিপ্রবলেমের -> ফযামিলিপ্রবলেমের

### ISSUE THREAD

**Issue by ShahriarDhruvo** [mnansary/bnUnicodeNormalizer#6]
ফ্যামিলিপ্রবলেমের ei word ta pass korle normalizer er output emon hoi -> ফযামিলিপ্রবলেমের

**Comment by mnansary** [comment]
fixed in v-0.0.19 :https://pypi.org/project/bnunicodenormalizer/0.0.19/
